//APP_SERVICE_WRAPPER
export const CONNECTION_CHANGED: string = 'CONNECTION_CHANGED';
export const APP_STATE_CHANGED: string = 'APP_STATE_CHANGED';
export const SHOW_LOADING_INDICATOR: string = 'SHOW_LOADING_INDICATOR';
export const HIDE_LOADING_INDICATOR: string = 'HIDE_LOADING_INDICATOR';
export const SHOW_ERROR: string = 'SHOW_ERROR';
export const HIDE_ERROR: string = 'HIDE_ERROR';
export const NONE_INTERNET_CONNECTION: string = 'NONE_INTERNET_CONNECTION';
// THEMING
export const TOGGLE_THEME: string = 'TOGGLE_THEME';
//LOGIN
export const AUTHORIZATION_STATE_CHANGED: string =
    'AUTHORIZATION_STATE_CHANGED';
export const AUTHORIZE_REQUEST: string = 'AUTHORIZE_REQUEST';
export const AUTHORIZE_SUCCESS: string = 'AUTHORIZE_SUCCESS';
export const AUTHORIZE_FAILURE: string = 'AUTHORIZE_FAILURE';
export const REFRESH_TOKEN_REQUEST: string = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: string = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE: string = 'REFRESH_TOKEN_FAILURE';
export const GET_DEVICE_REQUEST: string = 'GET_DEVICE_REQUEST';
export const GET_DEVICE_SUCCESS: string = 'GET_DEVICE_SUCCESS';
export const GET_DEVICE_FAILURE: string = 'GET_DEVICE_FAILURE';
export const REVOKE_TOKEN_REQUEST: string = 'REVOKE_TOKEN_REQUEST';
export const REVOKE_TOKEN_SUCCESS: string = 'REVOKE_TOKEN_SUCCESS';
export const REVOKE_TOKEN_FAILURE: string = 'REVOKE_TOKEN_FAILURE';
export const USER_ALREADY_AUTHORIZED: string = 'USER_ALREADY_AUTHORIZED';
export const GET_USERS_ME_REQUEST: string = 'GET_USERS_ME_REQUEST';
export const GET_USERS_ME_SUCCESS: string = 'GET_USERS_ME_SUCCESS';
export const GET_USERS_ME_FAILURE: string = 'GET_USERS_ME_FAILURE';
export const LOGOUT_USER: string = 'LOGOUT_USER';
//HOME
export const RENEW_LICENSE_REQUEST: string = 'RENEW_LICENSE_REQUEST';
export const RENEW_LICENSE_SUCCESS: string = 'RENEW_LICENSE_SUCCESS';
export const RENEW_LICENSE_FAILURE: string = 'RENEW_LICENSE_FAILURE';
export const GET_LAST_PAYMENT_REQUEST: string = 'GET_LAST_PAYMENT_REQUEST';
export const GET_LAST_PAYMENT_SUCCESS: string = 'GET_LAST_PAYMENT_SUCCESS';
export const GET_LAST_PAYMENT_FAILURE: string = 'GET_LAST_PAYMENT_FAILURE';
