# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# TODO: remove it later
# Bump fmt version to 12.1.0 to avoid build failure with Xcode 16.4+
# Patch all react-native podspecs that pin fmt to 11.0.2 before CocoaPods resolves dependencies
rn_path = File.join(__dir__, '..', 'node_modules', 'react-native')
Dir.glob(File.join(rn_path, '**', '*.podspec')).each do |podspec_path|
  content = File.read(podspec_path)
  if content.include?('"fmt", "11.0.2"') || (podspec_path.end_with?('fmt.podspec') && content.include?('"11.0.2"'))
    content.gsub!('"fmt", "11.0.2"', '"fmt", "12.1.0"')
    content.gsub!(/"11\.0\.2"/, '"12.1.0"') if podspec_path.end_with?('fmt.podspec')
    File.write(podspec_path, content)
  end
end

target 'FlorsemTime' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # To enable hermes on iOS, change `false` to `true` and then install pods
    # By default, Hermes is disabled on Old Architecture, and enabled on New Architecture.
    # You can enable/disable it manually by replacing with `true` or `false`.
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
